# Generated by Django 4.1.13 on 2024-01-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_profile_stockownership_profile_owned_stocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owned_stocks',
        ),
        migrations.AddField(
            model_name='stockownership',
            name='num_shares',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockownership',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
