# Generated by Django 4.1.13 on 2024-01-20 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trade_date',
            field=models.DateField(default=datetime.date(2024, 1, 20)),
            preserve_default=False,
        ),
    ]
