# Generated by Django 4.1.13 on 2024-01-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_stock_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
