# Generated by Django 4.1.13 on 2024-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_stock_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('closing_price', models.FloatField()),
                ('volume_weighted', models.FloatField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('num_trades', models.IntegerField()),
            ],
        ),
    ]
