# Generated by Django 4.1.13 on 2024-01-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='latest_closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
